# Generated by Django 3.0.5 on 2020-04-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20200412_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post Like/Dislike',
                'verbose_name_plural': 'Post Likes/Dislikes',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_unlikes',
        ),
        migrations.AddField(
            model_name='post',
            name='like_voters',
            field=models.ManyToManyField(related_name='like_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='unlike_voters',
            field=models.ManyToManyField(related_name='unlike_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Unlike',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
