# Generated by Django 3.0.5 on 2020-04-12 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20200412_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unlike_voters',
        ),
        migrations.AddField(
            model_name='post',
            name='dislike_voters',
            field=models.ManyToManyField(related_name='dislike_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
