# Generated by Django 3.0.5 on 2020-04-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200412_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
    ]
